create table public.venues_vacations (
	id int8 generated by default as identity primary key,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now(),
    venue_id int8 references public.venues not null,
	description text,
    "from" timestamp with time zone not null,
    "to" timestamp with time zone not null
);

-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table public.venues_vacations
  enable row level security;

create policy "venues_vacations are viewable by everyone" on public.venues_vacations
  for select using (true);